


services:
  backend:
    container_name: test_backend
    build:
      context: ./backend
    ports:
      - "8080:80"
    restart: always
    develop:
      watch:
        - path: backend
          action: sync
          target: /var/www/html
