FROM php:8.1 as dev

RUN apt-get update && apt-get install -y \
	git \
	unzip \
	libzip-dev
RUN docker-php-ext-install pdo pdo_mysql zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . /var/www/html

WORKDIR /var/www/html

RUN composer install

RUN chown -R www-data:www-data /var/www/html

RUN composer dump-autoload

CMD ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html/public"]
