FROM php:8.1 as dev

# Установка необходимых расширений и утилит
RUN apt-get update && apt-get install -y \
	git \
	unzip \
	libzip-dev
RUN docker-php-ext-install pdo pdo_mysql zip

# Установка Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Копирование файлов проекта
COPY . /var/www/html

WORKDIR /var/www/html

# Установка зависимостей
RUN composer install

# Установка прав
RUN chown -R www-data:www-data /var/www/html

CMD ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html/public"]
